// apps/desktop/src/lib/components/desktop/AppSidebar.svelte
<script lang="ts">
  import type { ProviderCommand, ProviderModel, ProviderQueueMode, SessionSummary } from "@h3code/agent-core";
  import type { ThinkingLevel } from "$lib/provider-model.js";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import {
    ArrowDown01Icon,
    ArrowRight01Icon,
    Add01Icon,
    FolderAddIcon,
    FolderCodeIcon,
    Moon02Icon,
    MoreHorizontalIcon,
    Search01Icon,
    Settings05Icon,
    Sun02Icon,
  } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";
  import { mode, toggleMode } from "mode-watcher";

  import ConfirmDeleteDialog from "$lib/components/desktop/ConfirmDeleteDialog.svelte";
  import ConnectionStatusIndicator from "$lib/components/desktop/ConnectionStatusIndicator.svelte";
  import VirtualSessionList from "$lib/components/desktop/VirtualSessionList.svelte";
  import { desktopState, type SidebarRepo } from "$lib/desktop-state.svelte";
  import { commandMenuController } from "$lib/command-menu-controller.svelte.js";
  import { getSessionDisplayTitle } from "$lib/session-display-title.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import * as ContextMenu from "$lib/components/ui/context-menu/index.js";
  import * as Sidebar from "$lib/components/ui/sidebar/index.js";

  let repoRemovalOpen = $state(false);
  let repoRemovalTarget = $state<SidebarRepo | undefined>();
  let sessionDeletionOpen = $state(false);
  let sessionDeletionTarget = $state<{ repo: SidebarRepo; session: SessionSummary } | undefined>();

  function requestRepoRemoval(repo: SidebarRepo) {
    repoRemovalTarget = repo;
    repoRemovalOpen = true;
  }

  function requestSessionDelete(repo: SidebarRepo, session: SessionSummary) {
    sessionDeletionTarget = { repo, session };
    sessionDeletionOpen = true;
  }

  const rowHorizontalPadding = "px-2";
  const rowButtonClass = `h-7 w-full rounded-md ${rowHorizontalPadding} text-[11px] leading-snug [&_svg]:size-3`;
  const repoRowButtonClass = `${rowButtonClass} !pr-8`;
  const sidebarInset = "px-2";
  const rowListGapClass = "gap-0.5";
  const iconActionClass =
    "grid size-7 shrink-0 place-items-center rounded-md text-sidebar-foreground outline-none hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 focus-visible:ring-sidebar-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:size-3";
  const contextMenuContentClass = "w-44";
  const themeToggleLabel = $derived(mode.current === "dark" ? "Switch to light mode" : "Switch to dark mode");

  async function openNewSessionLanding(repoPath?: string) {
    await desktopState.enterLanding(repoPath ? { repoPath } : {});
  }

  function handleSessionClick(sessionPath: string, repoPath: string) {
    if (page.url.pathname !== "/workspace") {
      void goto("/workspace");
    }

    void desktopState.handleSwitchSession(sessionPath, repoPath);
  }

  function openCommandMenu() {
    commandMenuController.open = true;
  }
</script>

<Sidebar.Sidebar collapsible="offcanvas">
  <Sidebar.Header class="shrink-0 border-b border-sidebar-border/50 p-0 {sidebarInset} py-1.5">
    <div class="flex h-7 items-center gap-0.5">
      <button
        type="button"
        aria-label="Open command center"
        title="Command center (⌘K)"
        class={iconActionClass}
        onclick={openCommandMenu}
      >
        <HugeiconsIcon icon={Search01Icon} strokeWidth={2} />
      </button>
      <button
        type="button"
        aria-label="New session"
        title="New session (⌘N)"
        disabled={desktopState.isBusy}
        class={iconActionClass}
        onclick={() => !desktopState.isBusy && openNewSessionLanding()}
      >
        <HugeiconsIcon icon={Add01Icon} />
      </button>
      <button
        type="button"
        aria-label="Add repository"
        title="Add repository"
        disabled={desktopState.isBusy}
        class={iconActionClass}
        onclick={() => desktopState.handleSelectRepo()}
      >
        <HugeiconsIcon icon={FolderAddIcon} />
      </button>
    </div>
  </Sidebar.Header>

  <Sidebar.Content class="min-h-0 flex-1">
    <Sidebar.Group class="flex min-h-0 flex-1 flex-col px-0 py-0">
      <div class="flex h-7 shrink-0 items-center pt-2 {sidebarInset}">
        <Sidebar.GroupLabel class="h-auto px-0 text-[11px] font-medium text-sidebar-foreground/80">
          Repositories
        </Sidebar.GroupLabel>
      </div>

      <Sidebar.GroupContent class="flex min-h-0 flex-1 flex-col">
        <nav aria-label="Workspace" class="flex min-h-0 flex-1 flex-col {sidebarInset}">
          <Sidebar.Menu
            aria-label="Repositories"
            class="min-h-0 flex-1 flex-col gap-0.5 overflow-y-auto overscroll-contain {rowListGapClass}"
          >
            {#if desktopState.repos.length === 0}
              <div class="flex flex-col gap-3 py-6 pr-1">
                <div class="space-y-1">
                  <p class="text-xs font-medium text-sidebar-foreground">No repositories yet</p>
                  <p class="text-[11px] leading-relaxed text-muted-foreground">
                    Add a folder on disk to browse Pi sessions and start work from here.
                  </p>
                </div>
                <Button
                  type="button"
                  variant="outline"
                  class="h-7 w-full justify-start gap-2 px-2 text-[11px]"
                  disabled={desktopState.isBusy}
                  onclick={() => !desktopState.isBusy && desktopState.handleSelectRepo()}
                >
                  <HugeiconsIcon icon={FolderAddIcon} class="size-3" />
                  Add repository
                </Button>
              </div>
            {:else}
              {#each desktopState.repos as repo}
                {@const isRepoActive = repo.path === desktopState.repoPath}
                {@const repoSessions = repo.sessions ?? []}
                <Sidebar.MenuItem>
                  <ContextMenu.Root>
                    <ContextMenu.Trigger class="w-full">
                      <Sidebar.MenuButton
                        size="sm"
                        isActive={isRepoActive}
                        tooltipContent={`${repo.name}${repo.path !== repo.name ? ` · ${repo.path}` : ""}`}
                        aria-expanded={repo.expanded ? "true" : "false"}
                        class={repoRowButtonClass}
                        aria-disabled={desktopState.isBusy}
                        onclick={() => !desktopState.isBusy && desktopState.toggleRepo(repo.path)}
                      >
                        {#if repo.expanded}
                          <HugeiconsIcon icon={ArrowDown01Icon} class="shrink-0 text-muted-foreground" />
                        {:else}
                          <HugeiconsIcon icon={ArrowRight01Icon} class="shrink-0 text-muted-foreground" />
                        {/if}
                        <HugeiconsIcon icon={FolderCodeIcon} class="shrink-0 text-muted-foreground/80" />
                        <span class={isRepoActive ? "min-w-0 flex-1 truncate font-medium" : "min-w-0 flex-1 truncate"}>
                          {repo.name}
                        </span>
                      </Sidebar.MenuButton>
                    </ContextMenu.Trigger>
                    <ContextMenu.Trigger>
                      <Sidebar.MenuAction
                        showOnHover
                        aria-label={`Actions for ${repo.name}`}
                        title="Repository actions"
                        disabled={desktopState.isBusy}
                        class="text-muted-foreground hover:text-sidebar-accent-foreground [&_svg]:size-3"
                      >
                        <HugeiconsIcon icon={MoreHorizontalIcon} />
                      </Sidebar.MenuAction>
                    </ContextMenu.Trigger>
                    <ContextMenu.Content class={contextMenuContentClass}>
                      <ContextMenu.Item
                        disabled={desktopState.isBusy}
                        onSelect={() => openNewSessionLanding(repo.path)}
                      >
                        New session
                      </ContextMenu.Item>
                      <ContextMenu.Separator />
                      <ContextMenu.Item
                        variant="destructive"
                        disabled={desktopState.isBusy}
                        onSelect={() => requestRepoRemoval(repo)}
                      >
                        Remove from startup
                      </ContextMenu.Item>
                    </ContextMenu.Content>
                  </ContextMenu.Root>

                  {#if repo.expanded}
                    <div class="shrink-0 pt-0.5 pl-3">
                      {#if repo.sessionsLoading}
                        <div
                          class="flex h-7 shrink-0 items-center gap-2 px-2 text-[11px] leading-snug text-muted-foreground"
                        >
                          <span
                            class="size-1.5 shrink-0 animate-pulse rounded-full bg-muted-foreground/45"
                            aria-hidden="true"
                          ></span>
                          <span class="truncate">Loading sessions</span>
                        </div>
                      {:else if repo.sessionsError}
                        <button
                          type="button"
                          class="flex h-7 w-full shrink-0 items-center rounded-md px-2 text-left text-[11px] leading-snug text-muted-foreground outline-none hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 focus-visible:ring-sidebar-ring"
                          onclick={() => desktopState.loadRepoSessions(repo.path)}
                        >
                          Could not load sessions. Retry
                        </button>
                      {:else if repoSessions.length === 0}
                        <div class="flex flex-col gap-2 py-2 pr-1">
                          <p class="text-[11px] text-muted-foreground">No sessions in this repo yet.</p>
                          <Button
                            type="button"
                            variant="ghost"
                            class="h-7 w-full justify-start gap-2 px-2 text-[11px]"
                            disabled={desktopState.isBusy}
                            onclick={() => !desktopState.isBusy && openNewSessionLanding(repo.path)}
                          >
                            <HugeiconsIcon icon={Add01Icon} class="size-3" />
                            Start session
                          </Button>
                        </div>
                      {:else}
                        <VirtualSessionList
                          {repo}
                          sessions={repoSessions}
                          onSessionClick={handleSessionClick}
                          onSessionDeleteRequest={requestSessionDelete}
                        />
                      {/if}
                    </div>
                  {/if}
                </Sidebar.MenuItem>
              {/each}
            {/if}
          </Sidebar.Menu>
        </nav>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Content>

  <Sidebar.Footer class="shrink-0 gap-1 border-t border-sidebar-border p-0 {sidebarInset} py-2">
    <div class="flex items-center justify-between gap-2 px-0.5">
      <ConnectionStatusIndicator status={desktopState.connectionStatus} class="min-w-0 text-[11px]" showLabel />
      <Button
        variant="ghost"
        size="icon-sm"
        class="shrink-0 text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
        onclick={toggleMode}
        aria-label={themeToggleLabel}
        title={themeToggleLabel}
      >
        <span class="relative grid size-3 place-items-center">
          <HugeiconsIcon
            icon={Sun02Icon}
            strokeWidth={2}
            className="scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90"
          />
          <HugeiconsIcon
            icon={Moon02Icon}
            strokeWidth={2}
            className="absolute scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0"
          />
        </span>
      </Button>
    </div>

    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Sidebar.MenuButton
          size="sm"
          tooltipContent="Settings"
          class="{rowButtonClass} text-muted-foreground"
          isActive={page.url.pathname === "/settings"}
        >
          {#snippet child({ props })}
            <a {...props} href="/settings">
              <HugeiconsIcon icon={Settings05Icon} />
              <span>Settings</span>
            </a>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Footer>

  <Sidebar.Rail />
</Sidebar.Sidebar>

<ConfirmDeleteDialog
  bind:open={repoRemovalOpen}
  title="Remove repo from startup?"
  description={`H3Code will remove ${repoRemovalTarget?.name ?? "this repo"} from the local index. PI sessions stay on disk and can be loaded again by adding the repo.`}
  confirmLabel="Remove from startup"
  busy={desktopState.isBusy}
  onConfirm={async () => {
    if (repoRemovalTarget) {
      await desktopState.removeRepoFromIndex(repoRemovalTarget.path);
      repoRemovalTarget = undefined;
    }
  }}
/>

<ConfirmDeleteDialog
  bind:open={sessionDeletionOpen}
  title="Delete PI session?"
  description={`This deletes ${sessionDeletionTarget ? getSessionDisplayTitle(sessionDeletionTarget.session) : "this session"} from PI. This cannot be undone.`}
  confirmLabel="Delete session"
  busy={desktopState.isBusy}
  onConfirm={async () => {
    if (sessionDeletionTarget) {
      await desktopState.deleteSession(sessionDeletionTarget.session.sessionRef, sessionDeletionTarget.repo.path);
      sessionDeletionTarget = undefined;
    }
  }}
/>

// apps/cloud/src/components/app-shell/AppSidebar.tsx
'use client'

import * as React from 'react'
import { Link, useRouterState } from '@tanstack/react-router'
import {
  ChevronDownIcon,
  ChevronRightIcon,
  MoonIcon,
  PanelLeftIcon,
  PlusIcon,
  SearchIcon,
  SettingsIcon,
  SunIcon,
} from 'lucide-react'

import { useTheme } from '#/components/theme-provider.tsx'
import { Button } from '#/components/ui/button.tsx'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '#/components/ui/collapsible.tsx'
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarRail,
  useSidebar,
} from '#/components/ui/sidebar.tsx'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '#/components/ui/tooltip.tsx'
import { listMockRepositories, listMockSessions } from '#/lib/mock/index.ts'
import type { MockSession } from '#/lib/mock/types.ts'
import { cn } from '#/lib/utils.ts'

const sidebarInset = 'px-2'

const iconClass = 'size-3 shrink-0'

const iconActionClass = cn(
  'size-7 shrink-0 rounded-md text-sidebar-foreground',
  'hover:bg-sidebar-accent hover:text-sidebar-accent-foreground',
  'focus-visible:ring-2 focus-visible:ring-sidebar-ring/30 focus-visible:outline-none',
  'active:translate-y-px motion-reduce:active:translate-y-0',
  'disabled:pointer-events-none disabled:opacity-50',
  '[&_svg]:size-3',
)

const menuRowClass = cn(
  'h-7 gap-1.5 px-2 text-[11px] font-normal leading-snug',
  '[&>svg]:!size-3',
  'active:translate-y-px motion-reduce:active:translate-y-0',
)

const groupLabelClass = cn(
  'h-auto px-0 text-[11px] font-medium uppercase tracking-wide',
  'text-sidebar-foreground/70',
)

const metaClass = 'text-[11px] leading-snug text-muted-foreground'

function useIconRail() {
  const { state, isMobile } = useSidebar()
  return state === 'collapsed' && !isMobile
}

function useIsSettingsRoute() {
  return useRouterState({
    select: (state) => state.location.pathname.startsWith('/app/settings'),
  })
}

function useActiveSessionId() {
  return useRouterState({
    select: (state) => {
      const match = /^\/app\/sessions\/([^/]+)/.exec(state.location.pathname)
      return match?.[1]
    },
  })
}

function SidebarCollapseTrigger() {
  const { toggleSidebar } = useSidebar()

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      className={iconActionClass}
      onClick={toggleSidebar}
      aria-label="Toggle sidebar"
      title="Toggle sidebar (⌘B)"
    >
      <PanelLeftIcon className={iconClass} aria-hidden />
    </Button>
  )
}

function NewSessionToolbarButton({ iconRail }: { iconRail: boolean }) {
  if (iconRail) {
    return (
      <SidebarToolbarAction label="New session" asChild>
        <Link to="/app" aria-label="New session" title="New session">
          <PlusIcon className={iconClass} aria-hidden />
        </Link>
      </SidebarToolbarAction>
    )
  }

  return (
    <Button
      type="button"
      variant="ghost"
      className={cn(
        iconActionClass,
        'ml-auto h-7 max-w-full items-center gap-1.5 px-2 text-[11px] font-medium',
      )}
      aria-label="New session"
      title="New session"
      asChild
    >
      <Link to="/app">
        <PlusIcon className={iconClass} aria-hidden />
        <span className="truncate">New session</span>
      </Link>
    </Button>
  )
}

function SidebarToolbarAction({
  label,
  className,
  asChild = false,
  children,
  ...props
}: React.ComponentProps<typeof Button> & {
  label: string
  asChild?: boolean
}) {
  const iconRail = useIconRail()
  const button = (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      asChild={asChild}
      className={cn(iconActionClass, className)}
      {...props}
    >
      {children}
    </Button>
  )

  if (iconRail) {
    return (
      <Tooltip>
        <TooltipTrigger asChild>{button}</TooltipTrigger>
        <TooltipContent side="right" align="center" className="text-xs">
          {label}
        </TooltipContent>
      </Tooltip>
    )
  }

  return button
}

function ThemeToggleButton() {
  const { resolvedTheme, toggleTheme } = useTheme()
  const themeToggleLabel =
    resolvedTheme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'

  return (
    <SidebarToolbarAction
      label={themeToggleLabel}
      className="relative shrink-0"
      aria-label={themeToggleLabel}
      title={themeToggleLabel}
      onClick={toggleTheme}
    >
      <SunIcon
        className={cn(
          iconClass,
          'scale-100 rotate-0 transition-all motion-reduce:transition-none dark:scale-0 dark:-rotate-90',
        )}
        aria-hidden
      />
      <MoonIcon
        className={cn(
          iconClass,
          'absolute scale-0 rotate-90 transition-all motion-reduce:transition-none dark:scale-100 dark:rotate-0',
        )}
        aria-hidden
      />
    </SidebarToolbarAction>
  )
}

function SessionSidebarLink({ session }: { session: MockSession }) {
  const activeSessionId = useActiveSessionId()
  const isActive = activeSessionId === session.id
  const title = session.summary.title ?? session.id
  const statusLabel = session.summary.status ?? 'idle'

  return (
    <SidebarMenuSubItem>
      <SidebarMenuSubButton
        asChild
        size="sm"
        isActive={isActive}
        className={cn(
          menuRowClass,
          'h-auto min-h-7 flex-col items-start gap-0 py-1.5',
          'text-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground',
        )}
      >
        <Link
          to="/app/sessions/$sessionId"
          params={{ sessionId: session.id }}
          title={title}
        >
          <span className="w-full truncate">{title}</span>
          {(session.preview ?? statusLabel !== 'idle') ? (
            <span className={cn('w-full truncate', metaClass)}>
              {session.preview ?? statusLabel}
            </span>
          ) : null}
        </Link>
      </SidebarMenuSubButton>
    </SidebarMenuSubItem>
  )
}

function RepositoryCollapsible({
  repositoryId,
  name,
  sessions,
  defaultOpen = false,
}: {
  repositoryId: string
  name: string
  sessions: readonly MockSession[]
  defaultOpen?: boolean
}) {
  const [open, setOpen] = React.useState(defaultOpen)

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <SidebarMenuItem>
        <div className="flex w-full min-w-0 items-center gap-0.5">
          <CollapsibleTrigger asChild>
            <SidebarMenuButton
              size="sm"
              tooltip={name}
              className={cn(menuRowClass, 'min-w-0 flex-1')}
              aria-expanded={open}
            >
              {open ? (
                <ChevronDownIcon
                  className={cn(iconClass, 'text-muted-foreground')}
                  aria-hidden
                />
              ) : (
                <ChevronRightIcon
                  className={cn(iconClass, 'text-muted-foreground')}
                  aria-hidden
                />
              )}
              <span className="min-w-0 flex-1 truncate">{name}</span>
            </SidebarMenuButton>
          </CollapsibleTrigger>
          <SidebarToolbarAction
            label={`New session in ${name}`}
            asChild
            className="shrink-0"
          >
            <Link
              to="/app"
              search={{ repo: repositoryId }}
              aria-label={`New session in ${name}`}
              title={`New session in ${name}`}
            >
              <PlusIcon className={iconClass} aria-hidden />
            </Link>
          </SidebarToolbarAction>
        </div>
        <CollapsibleContent>
          <SidebarMenuSub className="mx-0 gap-0.5 border-0 px-0 py-0.5 pl-5">
            {sessions.length === 0 ? (
              <SidebarMenuSubItem>
                <p className={cn('px-2 py-1', metaClass)}>No sessions yet</p>
              </SidebarMenuSubItem>
            ) : (
              sessions.map((session) => (
                <SessionSidebarLink key={session.id} session={session} />
              ))
            )}
          </SidebarMenuSub>
        </CollapsibleContent>
      </SidebarMenuItem>
    </Collapsible>
  )
}

function RepositoriesEmptyState() {
  return (
    <div className="flex flex-col gap-3 py-6 pr-1">
      <div className="space-y-1">
        <p className="text-xs font-medium text-sidebar-foreground">
          No repositories yet
        </p>
        <p className={cn(metaClass, 'leading-relaxed')}>
          Connect a repository to browse Pi sessions and start work from here.
        </p>
      </div>
      <Button
        type="button"
        variant="outline"
        className="h-7 w-full justify-start gap-2 border-sidebar-border px-2 text-[11px] shadow-none active:translate-y-px motion-reduce:active:translate-y-0"
        asChild
      >
        <Link to="/app">
          <PlusIcon className={iconClass} aria-hidden />
          Add repository
        </Link>
      </Button>
    </div>
  )
}

export function AppSidebar() {
  const iconRail = useIconRail()
  const isSettingsActive = useIsSettingsRoute()
  const repositories = listMockRepositories()
  const hasRepositories = repositories.length > 0

  return (
    <Sidebar collapsible="icon" className="border-sidebar-border">
      <SidebarHeader
        className={cn(
          'shrink-0 gap-0 border-b border-sidebar-border/50 p-0',
          sidebarInset,
          'py-1.5',
        )}
      >
        <div
          className={cn(
            'flex w-full min-w-0 items-center gap-0.5',
            iconRail ? 'flex-col' : 'h-7',
          )}
        >
          <SidebarCollapseTrigger />
          <SidebarToolbarAction
            label="Search"
            aria-label="Search"
            title="Search"
          >
            <SearchIcon className={iconClass} aria-hidden />
          </SidebarToolbarAction>
          <NewSessionToolbarButton iconRail={iconRail} />
        </div>
      </SidebarHeader>

      <SidebarContent className="min-h-0 flex-1 gap-0 overflow-hidden">
        {!iconRail ? (
          <SidebarGroup className="flex min-h-0 flex-1 flex-col p-0">
            <div
              className={cn(
                'flex h-7 shrink-0 items-center pt-2',
                sidebarInset,
              )}
            >
              <SidebarGroupLabel className={groupLabelClass}>
                Repositories
              </SidebarGroupLabel>
            </div>
            <SidebarGroupContent className="flex min-h-0 flex-1 flex-col">
              <nav
                aria-label="Repositories"
                className={cn(
                  'flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain pb-2',
                  sidebarInset,
                )}
              >
                {!hasRepositories ? (
                  <RepositoriesEmptyState />
                ) : (
                  <SidebarMenu className="gap-0.5">
                    {repositories.map((repo) => (
                      <RepositoryCollapsible
                        key={repo.id}
                        repositoryId={repo.id}
                        name={repo.name}
                        sessions={listMockSessions(repo.id)}
                        defaultOpen={repo.defaultOpen}
                      />
                    ))}
                  </SidebarMenu>
                )}
              </nav>
            </SidebarGroupContent>
          </SidebarGroup>
        ) : null}
      </SidebarContent>

      <SidebarFooter
        className={cn(
          'shrink-0 gap-1 border-t border-sidebar-border/50 p-0',
          iconRail ? 'px-1 py-2' : cn(sidebarInset, 'py-2'),
        )}
      >
        {iconRail ? (
          <div className="flex flex-col items-center gap-1">
            <SidebarToolbarAction label="Settings" asChild>
              <Link to="/app/settings" aria-label="Settings" title="Settings">
                <SettingsIcon className={iconClass} aria-hidden />
              </Link>
            </SidebarToolbarAction>
            <ThemeToggleButton />
          </div>
        ) : (
          <div className="flex items-center gap-0.5">
            <SidebarMenu className="min-w-0 flex-1">
              <SidebarMenuItem>
                <SidebarMenuButton
                  asChild
                  size="sm"
                  isActive={isSettingsActive}
                  tooltip="Settings"
                  className={cn(
                    menuRowClass,
                    'text-muted-foreground data-[active=true]:text-sidebar-accent-foreground',
                  )}
                >
                  <Link to="/app/settings">
                    <SettingsIcon className={iconClass} aria-hidden />
                    <span>Settings</span>
                  </Link>
                </SidebarMenuButton>
              </SidebarMenuItem>
            </SidebarMenu>
            <ThemeToggleButton />
          </div>
        )}
      </SidebarFooter>

      <SidebarRail />
    </Sidebar>
  )
}
