// apps/cloud/src/components/workspace/LandingRepoSelector.tsx
'use client'

import {
  PromptInputSelect,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectTrigger,
  PromptInputSelectValue,
} from '#/components/ai-elements/prompt-input.tsx'
import type { DemoRepository } from '#/lib/demo-repositories.ts'
import { cn } from '#/lib/utils.ts'

/** Matches AppSidebar menu rows (h-7, 12px label). */
const repoTriggerClass = cn(
  'h-7 max-w-[16rem] gap-1.5 px-2 text-[12px] font-normal leading-snug shadow-none',
  'text-foreground data-[placeholder]:text-muted-foreground',
  'hover:bg-muted hover:text-foreground',
  'aria-expanded:bg-muted',
  'focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:outline-none',
  'disabled:cursor-not-allowed disabled:opacity-50',
)

type LandingRepoSelectorProps = {
  repositories: readonly DemoRepository[]
  value: string | undefined
  onValueChange: (repositoryId: string | undefined) => void
  disabled?: boolean
  className?: string
}

export function LandingRepoSelector({
  repositories,
  value,
  onValueChange,
  disabled = false,
  className,
}: LandingRepoSelectorProps) {
  const hasRepositories = repositories.length > 0
  const selectedName = value ? repositories.find((r) => r.id === value)?.name : undefined

  return (
    <PromptInputSelect
      value={value ?? ''}
      onValueChange={(next) => onValueChange(next || undefined)}
      disabled={disabled || !hasRepositories}
    >
      <PromptInputSelectTrigger
        className={cn(repoTriggerClass, className)}
        aria-label="Select repository"
        title={selectedName ?? 'Select repository'}
      >
        <PromptInputSelectValue placeholder="Select repository" />
      </PromptInputSelectTrigger>
      <PromptInputSelectContent align="start" className="min-w-[12rem] text-xs">
        {repositories.map((repo) => (
          <PromptInputSelectItem
            key={repo.id}
            value={repo.id}
            className="h-7 text-xs leading-snug"
          >
            {repo.name}
          </PromptInputSelectItem>
        ))}
      </PromptInputSelectContent>
    </PromptInputSelect>
  )
}

// apps/desktop/src/lib/components/desktop/LandingRepoSelector.svelte
<script lang="ts">
  import { FolderAddIcon, FolderCodeIcon } from "@hugeicons/core-free-icons";
  import { HugeiconsIcon } from "@hugeicons/svelte";

  import ComposerPillButton from "$lib/components/desktop/ComposerPillButton.svelte";
  import { desktopState } from "$lib/desktop-state.svelte";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import { cn } from "$lib/utils";

  type Props = {
    disabled?: boolean;
  };

  let { disabled = false }: Props = $props();

  let open = $state(false);

  const repoOptions = $derived(desktopState.repos);
  const label = $derived(desktopState.landingRepoName ?? "Select repository");

  async function handleAddRepository() {
    await desktopState.addRepoFromLanding();
  }
</script>

<DropdownMenu.Root bind:open>
  <DropdownMenu.Trigger
    type="button"
    {disabled}
    class={cn(
      "inline-flex border-0 bg-transparent p-0 shadow-none outline-none",
      "focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none",
    )}
    aria-label="Select repository"
    title={desktopState.landingRepoPath ?? "Select repository"}
  >
    <ComposerPillButton
      {label}
      {open}
      {disabled}
      variant="footer"
      maxWidthClass="max-w-[14rem]"
      ariaLabel="Select repository"
    />
  </DropdownMenu.Trigger>

  <DropdownMenu.Content
    side="top"
    align="start"
    sideOffset={8}
    class="!w-auto min-w-64 max-w-80 shadow-none ring-1 ring-border/50"
  >
    <DropdownMenu.Group>
      <DropdownMenu.GroupHeading
        class="px-2 py-1.5 text-[10px] font-medium uppercase tracking-wide text-muted-foreground"
      >
        Repository
      </DropdownMenu.GroupHeading>
      {#if repoOptions.length === 0}
        <div class="px-2 py-2 text-xs text-muted-foreground">No repositories yet.</div>
      {:else}
        <DropdownMenu.RadioGroup
          value={desktopState.landingRepoPath ?? ""}
          onValueChange={(value) => {
            desktopState.landingRepoPath = value || undefined;
          }}
        >
          {#each repoOptions as repo (repo.path)}
            <DropdownMenu.RadioItem value={repo.path} class="items-start py-2">
              <HugeiconsIcon icon={FolderCodeIcon} class="mt-0.5 size-3 shrink-0 text-muted-foreground" data-icon />
              <span class="min-w-0 flex-1 text-left">
                <span class="block truncate text-xs font-medium leading-tight text-foreground">{repo.name}</span>
                <span
                  class="mt-0.5 block truncate font-mono text-[10px] leading-tight text-muted-foreground"
                  title={repo.path}
                >
                  {repo.path}
                </span>
              </span>
            </DropdownMenu.RadioItem>
          {/each}
        </DropdownMenu.RadioGroup>
      {/if}
    </DropdownMenu.Group>

    <DropdownMenu.Separator />

    <DropdownMenu.Item
      class="gap-2"
      onSelect={() => {
        void handleAddRepository();
      }}
    >
      <HugeiconsIcon icon={FolderAddIcon} class="size-3.5 shrink-0 text-muted-foreground" data-icon />
      <span>Add repository…</span>
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>
