// apps/cloud/src/components/ai-elements/toolbar.tsx
import { cn } from "#/lib/utils.ts";
import { NodeToolbar, Position } from "@xyflow/react";
import type { ComponentProps } from "react";

type ToolbarProps = ComponentProps<typeof NodeToolbar>;

export const Toolbar = ({ className, ...props }: ToolbarProps) => (
  <NodeToolbar
    className={cn(
      "flex items-center gap-1 rounded-sm border bg-background p-1.5",
      className
    )}
    position={Position.Bottom}
    {...props}
  />
);

// apps/desktop/src/lib/components/ai-elements/prompt-input/layout/Toolbar.svelte
<script lang="ts">
	import { cn } from "$lib/utils";

	interface Props {
		class?: string;
		children?: import("svelte").Snippet;
	}

	let { class: className, children, ...props }: Props = $props();
	// indexing
</script>

<div class={cn("flex h-10 items-center justify-between border-t border-border/50 px-3", className)} {...props}>
	{#if children}
		{@render children()}
	{/if}
</div>
